Mappings:
  RegionMap:  # MapName with TopLevelKeys(unique) & SecondLevelKey:Value pairs
    us-east-1:
      AMI: ami-0df435f331839b2d6  # AmazonLinux 2023 AMI in N.Virginia region
    us-west-1:
      AMI: ami-0c87a756f3fd22df2
    us-west-2:
      AMI: ami-09ac7e749b0a8d2a1  # AmazonLinux 2023 AMI in Oregon region
    eu-west-1:
      AMI: ami-0dab0800aa38826f2
    eu-central-1:
      AMI: ami-0fb820135757d28fd  # AmazonLinux 2023 AMI in EU Frankfurt region
Resources:
  Ec2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: t2.micro
      ImageId:
        Fn::FindInMap:  # syntax Fn::FindInMap: [ MapName, TopLevelKey, SecondLevelKey ]
        - RegionMap
        - !Ref AWS::Region  # passsing a pseudoparam for region as TopLevelKey
        - AMI # returning the value from the corresponding SecondLevelKey:Value pair
      SecurityGroups: 
        - !Ref MySecurityGroup
      Tags:
        - Key: "Name"
          Value: !Join 
            - "-EC2-"
            - - !Ref AWS::AccountId # Pseudo parameters are predefined by Cfn
              - !Ref AWS::Region
  MySecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Enable SSH access via port 22
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: 0.0.0.0/0